baseURL = 'https://mialunachen.github.io/'
languageCode = 'en-us'
title = 'mialunachen'
theme = 'lightbi-hugo'
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "02 Jan 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true 
summaryLength  = "9"
gcse = false
Lastmod = false
rss = false 
pagination = "10"
hideAuthor = false

description="Your can add your website description here."


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Author]
  name = "Mia Luna Chen"
  website = "https://binovarghese.com/"
  email = "mialuna@mit.edu"
  # facebook = "username"
  instagram = "mialunachen"
  youtube = "user/username" # or channel/channelname
  # twitter = "username"
  # threads = "username"
  linkedin = "mia-chen-15b99a122"
  github = "username"
  #gitlab = "username"
  #bitbucket = "username"
  #reddit = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

 # [[menu.main]]
 #  name = "Notes"
 #   url = "/notes/"
 #   weight = 2

[[menu.main]]
    name = "Blog"
    url = "/Collections/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4


[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    

